#+AUTHOR: Daniel Persson
#+EMAIL: daniel@silvertejp.org

* Git Demo Tools
  Git Demo Tools is a suite of tools useful for teaching and demoing
  [[https://git-scm.com/][git]].

** Live log
   Live log is started with the =git livelog= command, and will start
   a continuously updating git tree with enough information to make it
   useful, but still sparse enough to fit on a screen next to a shell.

   The command takes two parameters, the maximum number of entries
   (lines) to show, and the update interval in seconds. The default
   number of lines is 20, and the default update interval is 1 second.

** Repo switcher
   - The =git repo= command takes the name of an example repository as
     an argument, and will instantly replace the current repository
     with the specified example.
   - The =git repo-save= command takes the name of a new example
     repository as an argument, and saves the current repository as
     that name.
   - The =git repo-list= command lists all saved example repositories.

*** Example repository structure
    Repositories are stored in the path specified by =$EXAMPLEREPOS=,
    and should consist of a directory (the name of the directory will
    be the name of the example) containing a =metadata= directory
    (with a bare git repo inside) and a =tree= directory containing
    the working tree.


* Installation
  - Clone this repository and add the bin directory to your =$PATH=.
  - Update =$EXAMPLEREPOS= to point to the directory with your
    examples.
